# Generated by Django 4.2.13 on 2024-07-26 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logincredentials',
            name='shopping_cart',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='items_ordered',
            field=models.JSONField(default=list),
        ),
    ]
