# Generated by Django 4.2.13 on 2024-07-26 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_logincredentials_shopping_cart_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
