# Generated by Django 4.2.13 on 2024-07-30 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_delete_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableTimeSlots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], max_length=20)),
                ('capacity', models.IntegerField(default=10)),
            ],
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='reward_change',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='logincredentials',
            name='reward_points',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_count', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('canceled', 'Canceled'), ('completed', 'Completed')], default='confirmed', max_length=15)),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.availabletimeslots')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.logincredentials')),
            ],
        ),
    ]
